

const rawFoodThemes = [
    {name: "Frank's Food Theme", description: "High quality local food"},
    {name: "Nero's Food Theme", description: "Local and delicious"}
    // {name: "Food Demo Theme 3", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 4", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 5", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 6", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 7", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 8", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 9", description: "I have seeded random theme items"},
    // {name: "Food Demo Theme 10", description: "I have seeded random theme items"}
];



const rawFoodThemeItems = [
{text:"Biscuit"},
{text:"Bread"},
{text:"Apple butter"},
{text:"Baked potato"},
{text:"Barbecue "},
{text:"Bear claw"},
{text:"Blue cheese dressing"},
{text:"Breakfast burrito"},
{text:"Buffalo wing"},
{text:"Butter cookie"},
{text:"Cajun cuisine"},
{text:"Cheese dog"},
{text:"Cheese fries"},
{text:"Cheesesteak"},
{text:"Chicago-style pizza"},
{text:"Chicken and waffles"},
{text:"Chicken parmigiana"},
{text:"Chicken sandwich"},
{text:"Chili dog"},
{text:"Chimichanga"},
{text:"Chinese food"},
{text:"Chips and dip"},
{text:"Milk chocolate"},
{text:"White chocolate"},
{text:"Chocolate chip cookies"},
{text:"City chicken"},
{text:"Clam chowder"},
{text:"Club sandwich"},
{text:"Coleslaw"},
{text:"Corn chowder"},
{text:"Corn dog"},
{text:"Corn flakes"},
{text:"Corned beef"},
{text:"Crab cake"},
{text:"Deviled egg"},
{text:"Doughnut"},
{text:"Eggo"},
{text:"Eggs Benedict"},
{text:"Energy bar"},
{text:"Fajita"},
{text:"Fortune cookie"},
{text:"French dip"},
{text:"Fried chicken"},
{text:"Fried fish"},
{text:"Garden salad"},
{text:"Goulash"},
{text:"Green bean casserole"},
{text:"Grilled cheese"},
{text:"Grits"},
{text:"Hamburger"},
{text:"Home fries"},
{text:"Ice cream cake"},
{text:"Italian dressing"},
{text:"Jell-O"},
{text:"Jerky"},
{text:"Liver and onions"},
{text:"Lobster roll"},
{text:"Macaroni and cheese"},
{text:"Mashed potato"},
{text:"Meatloaf"},
{text:"Milkshake"},
{text:"Mozzarella sticks"},
{text:"Muffin"},
{text:"Onion ring"},
{text:"Oreo"},
{text:"Oysters"},
{text:"Pancakes"},
{text:"Pastrami"},
{text:"Peanut butter"},
{text:"Pepperoni"},
{text:"Pickles"},
{text:"Pigs in blankets"},
{text:"Pizza strips"},
{text:"Pop-Tarts"},
{text:"Popcorn"},
{text:"Pork and beans"},
{text:"Potato salad"},
{text:"Protein bar"},
{text:"Pulled pork"},
{text:"Pumpkin pie"},
{text:"Ranch dressing"},
{text:"Ribs"},
{text:"Russian dressing"},
{text:"Salisbury steak"},
{text:"Sandwich"},
{text:"Seafood cocktail"},
{text:"Sloppy joe"},
{text:"Soul food"},
{text:"Sour cream"},
{text:"Steak"},
{text:"Steamed clams"},
{text:"Stuffed peppers"},
{text:"Succotash"},
{text:"Surf and turf"},
{text:"Toaster Strudel"},
{text:"Tuna casserole"},
{text:"Turkey"},
{text:"Waffle"},

];

module.exports = {
    themes: rawFoodThemes,
    themeItems: rawFoodThemeItems
};