const rawScavengerThemes = [
    {name: "Craig's Scavenger Hunt", description: "Find these 9 random items"},
    {name: "Scotts's Scavenger Hunt", description: "Beat me if you can!"}
    // {name: "Scavenger Demo Theme 3", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 4", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 5", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 6", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 7", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 8", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 9", description: "I have seeded random theme items"},
    // {name: "Scavenger Demo Theme 10", description: "I have seeded random theme items"}
];

const rawScavengerThemeItems = [
{text:"1999 penny"},
{text:"Target bag"},
{text:"paper clip"},
{text:"band-aid"},
{text:"sweet-n-low packet"},
{text:"Christmas plate"},
{text:"Post it note"},
{text:"old shoe"},
{text:".25 coupon"},
{text:"blue balloon"},
{text:"lolipop"},
{text:"plastic spoon"},
{text:"birthday candle"},
{text:"pink crayon"},
{text:"Ziploc bag"},
{text:"envelope"},
{text:"toilet paper roll"},
{text:"comic strip"},
{text:"artificial flower"},
{text:"dryer sheet"},
{text:"piece of string"},
{text:"ketchup packet"},
{text:"ribbon or bow"},
{text:"noisemaker"},
{text:"straw"},
{text:"package of Raman noodles"},
{text:"clothespin"},
{text:"staple"},
{text:"paper cup"},
{text:"paper towel roll"},
{text:"nail"},
{text:"sock"},
{text:"froot loop cereal"},
{text:"napkin"},
{text:"ball"},
{text:"pencil"},
{text:"piece of candy"},
{text:"picture of a dog"},
{text:"paper sack"},
{text:"gift wrap bag"},
{text:"gumball"},
{text:"piece of jewelry"},
{text:"Sudoku puzzle"},
{text:"business card"},
{text:"empty water bottle"},
{text:"marble"},
{text:"yarn"},
{text:"sticker"},
{text:"birthday present"},
{text:"Acorn"},
{text:"Yellow Flower"},
{text:"Orange Leaf"},
{text:"Feather"},
{text:"Red Berry"},
{text:"Squash"},
{text:"Carrot"},
{text:"Apple"},
{text:"Candle"},
{text:"Orange Jellybean"},
{text:"Red Lipstick"},
{text:"Yellow Crayon"},
{text:"Magazine"},
{text:"Cinnamon Stick"}
];




module.exports = {
    themes: rawScavengerThemes,
    themeItems: rawScavengerThemeItems
};